# Generated by Django 6.0.3 on 2026-04-10 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeecode', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('attendancecode', models.CharField(max_length=50, unique=True)),
                ('warehouseid', models.CharField(blank=True, max_length=50, null=True)),
                ('latlong', models.CharField(blank=True, max_length=50, null=True)),
                ('embedding', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'RegisteredEmployee',
            },
        ),
        migrations.CreateModel(
            name='Warehousedetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=50)),
                ('latlong', models.CharField(default='0,0', max_length=50)),
                ('status', models.IntegerField(default=1)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Warehousedetails',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendanceApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timein', models.TimeField(blank=True, null=True)),
                ('fulltimeout', models.TimeField(blank=True, null=True)),
                ('deviceinfo', models.CharField(blank=True, max_length=200, null=True)),
                ('assignedlocation', models.CharField(blank=True, max_length=100, null=True)),
                ('checkinlocation', models.CharField(blank=True, max_length=100, null=True)),
                ('checkoutlocation', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='attendancecode', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.registeredemployee', to_field='attendancecode')),
            ],
            options={
                'db_table': 'EmployeeAttendanceApp',
                'ordering': ['-date', '-timein'],
            },
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
