# Generated by Django 6.0.3 on 2026-04-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_registeredemployee_warehousedetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendanceapp',
            name='fulltimeout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeattendanceapp',
            name='timein',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
