# Generated by Django 6.0.3 on 2026-05-07 07:38

import django.db.models.deletion
from django.db import migrations, models


def consolidate_duplicate_attendance(apps, schema_editor):
    Attendance = apps.get_model('attendance', 'EmployeeAttendanceApp')
    from django.db.models import Count

    duplicates = (
        Attendance.objects
        .values('employee_id', 'date')
        .annotate(total=Count('id'))
        .filter(total__gt=1)
    )

    for duplicate in duplicates:
        records = list(
            Attendance.objects
            .filter(employee_id=duplicate['employee_id'], date=duplicate['date'])
            .order_by('timein', 'created_at', 'id')
        )
        if not records:
            continue

        keeper = records[0]
        timeins = [record.timein for record in records if record.timein is not None]
        timeouts = [record.fulltimeout for record in records if record.fulltimeout is not None]
        keeper.timein = min(timeins) if timeins else keeper.timein
        keeper.fulltimeout = max(timeouts) if timeouts else keeper.fulltimeout

        first_checkin = next((record.checkinlocation for record in records if record.checkinlocation), None)
        last_checkout = next((record.checkoutlocation for record in reversed(records) if record.checkoutlocation), None)
        keeper.checkinlocation = first_checkin or keeper.checkinlocation
        keeper.checkoutlocation = last_checkout or keeper.checkoutlocation
        keeper.save()

        Attendance.objects.filter(id__in=[record.id for record in records[1:]]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_employeeattendanceapp_fulltimeout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendanceapp',
            name='employee',
            field=models.ForeignKey(db_column='attendancecode', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='attendance.registeredemployee', to_field='attendancecode'),
        ),
        migrations.AddIndex(
            model_name='employeeattendanceapp',
            index=models.Index(fields=['employee', 'date'], name='att_emp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeattendanceapp',
            index=models.Index(fields=['date'], name='att_date_idx'),
        ),
        migrations.RunPython(consolidate_duplicate_attendance, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='employeeattendanceapp',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_attendance_per_date'),
        ),
    ]
