# Generated by Django 6.0.3 on 2026-05-12 07:53

import django.db.models.deletion
from django.db import migrations, models


def backfill_legacy_face_embeddings(apps, schema_editor):
    RegisteredEmployee = apps.get_model("attendance", "RegisteredEmployee")
    EmployeeFaceEmbedding = apps.get_model("attendance", "EmployeeFaceEmbedding")

    for employee in RegisteredEmployee.objects.exclude(embedding__isnull=True).exclude(embedding=""):
        EmployeeFaceEmbedding.objects.get_or_create(
            employee=employee,
            sample_label="legacy_primary",
            defaults={
                "embedding": employee.embedding,
                "is_primary": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_alter_employeeattendanceapp_employee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeFaceEmbedding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("embedding", models.TextField()),
                ("sample_label", models.CharField(default="primary", max_length=50)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_embeddings",
                        to="attendance.registeredemployee",
                    ),
                ),
            ],
            options={
                "db_table": "EmployeeFaceEmbedding",
                "ordering": ["-is_primary", "created_at"],
            },
        ),
        migrations.RunPython(backfill_legacy_face_embeddings, migrations.RunPython.noop),
    ]
