# Generated by Django 6.0.3 on 2026-05-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_employee_fk_to_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendanceapp',
            name='matched_warehouse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendanceapp',
            name='submitted_attendancecode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendanceapp',
            name='submitted_employeecode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendanceapp',
            name='verification_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendanceapp',
            name='verification_decision',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendanceapp',
            name='verification_margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendanceapp',
            name='verification_method',
            field=models.CharField(default='employee_code_face', max_length=30),
        ),
    ]
