# Generated by Django 6.0.3 on 2026-05-12 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_employeeattendanceapp_matched_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefaceembedding',
            name='capture_source',
            field=models.CharField(default='mobile_enrollment', max_length=30),
        ),
        migrations.AddField(
            model_name='employeefaceembedding',
            name='quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeefaceembedding',
            name='sample_order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='AttendanceVerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_employeecode', models.CharField(blank=True, max_length=50, null=True)),
                ('submitted_attendancecode', models.CharField(blank=True, max_length=50, null=True)),
                ('currentlocation', models.CharField(blank=True, max_length=100, null=True)),
                ('matched_warehouse', models.CharField(blank=True, max_length=50, null=True)),
                ('deviceinfo', models.CharField(blank=True, max_length=200, null=True)),
                ('verification_confidence', models.FloatField(blank=True, null=True)),
                ('verification_margin', models.FloatField(blank=True, null=True)),
                ('verification_decision', models.CharField(max_length=50)),
                ('verification_method', models.CharField(default='employee_code_face', max_length=30)),
                ('attempt_status', models.CharField(max_length=30)),
                ('failure_reason', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_attempts', to='attendance.registeredemployee')),
            ],
            options={
                'db_table': 'AttendanceVerificationAttempt',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='verify_attempt_time_idx'), models.Index(fields=['attempt_status'], name='verify_attempt_status_idx')],
            },
        ),
    ]
