# Generated by Django 6.0.3 on 2026-05-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_employeefaceembedding_capture_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredemployee',
            name='embedding',
        ),
    ]
