# Generated by Django 6.0.3 on 2026-05-12 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_remove_registeredemployee_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendanceapp',
            name='corrected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendanceapp',
            name='corrected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeattendanceapp',
            name='correction_action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendanceapp',
            name='correction_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeefaceembedding',
            name='angle_label',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employeefaceembedding',
            name='capture_session_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
