# Generated by Django 6.0.3 on 2026-05-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_employeeattendanceapp_corrected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendanceapp',
            name='checkin_warehouse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendanceapp',
            name='checkout_warehouse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
